runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /js
  static_dir: js

- url: /.*
  script: form.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: 2.7.11
- name: pycrypto
  version: 2.6
# [END libraries]

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'clerkship-shuffle'